[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
votara = "8wdEVo3K6tALZjmxBtNH7DHVfYRGhSBFVbUkwRzVBMZq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
